# Introduction to Julia, part 2

<img src="./julia_logo.png" align="center" width="400"/>

https://julialang.org

## Matrices and vectors

### Dimensions

In [1]:
x = randn(5, 3)

5×3 Matrix{Float64}:
 -1.10531   -1.12618   -0.280221
 -0.346053   1.31651    0.0732267
  0.742706   0.135561  -0.994282
 -1.70301   -0.727118   2.31766
  0.745916  -1.12055    0.140907

In [2]:
size(x)

(5, 3)

In [3]:
size(x, 1) # nrow() in R

5

In [4]:
size(x, 2) # ncol() in R

3

In [5]:
# total number of elements
length(x)

15

### Indexing

In [6]:
# 5 × 5 matrix of random Normal(0, 1)
x = randn(5, 5)

5×5 Matrix{Float64}:
 -0.384079   0.540629   0.003503  -0.0534454   0.382545
  1.56377    0.876571   1.01683    1.84941     0.567994
 -0.687446   0.313884  -0.306218  -1.77579    -0.088558
  0.563199  -1.18005   -0.895966   0.217129    0.816159
  0.598676  -1.44407    0.318821  -0.211098   -0.322778

In [7]:
# first column
x[:, 1]

5-element Vector{Float64}:
 -0.3840786272805249
  1.563770258704395
 -0.6874461657292189
  0.5631993022368884
  0.5986762237099348

In [8]:
# first row
x[1, :]

5-element Vector{Float64}:
 -0.3840786272805249
  0.5406293111966782
  0.003503004059083037
 -0.05344542595632667
  0.3825449134563247

In [9]:
# sub-array
x[1:2, 2:3]

2×2 Matrix{Float64}:
 0.540629  0.003503
 0.876571  1.01683

In [10]:
# getting a subset of a matrix creates a copy, but you can also create "views"
z = view(x, 1:2, 2:3)

2×2 view(::Matrix{Float64}, 1:2, 2:3) with eltype Float64:
 0.540629  0.003503
 0.876571  1.01683

In [11]:
# same as
@views z = x[1:2, 2:3]

2×2 view(::Matrix{Float64}, 1:2, 2:3) with eltype Float64:
 0.540629  0.003503
 0.876571  1.01683

In [12]:
# change in z (view) changes x as well
z[2, 2] = 0.0
x

5×5 Matrix{Float64}:
 -0.384079   0.540629   0.003503  -0.0534454   0.382545
  1.56377    0.876571   0.0        1.84941     0.567994
 -0.687446   0.313884  -0.306218  -1.77579    -0.088558
  0.563199  -1.18005   -0.895966   0.217129    0.816159
  0.598676  -1.44407    0.318821  -0.211098   -0.322778

In [13]:
# y points to same data as x
y = x

5×5 Matrix{Float64}:
 -0.384079   0.540629   0.003503  -0.0534454   0.382545
  1.56377    0.876571   0.0        1.84941     0.567994
 -0.687446   0.313884  -0.306218  -1.77579    -0.088558
  0.563199  -1.18005   -0.895966   0.217129    0.816159
  0.598676  -1.44407    0.318821  -0.211098   -0.322778

In [14]:
# x and y point to same data
pointer(x), pointer(y)

(Ptr{Float64} @0x000000010df5b890, Ptr{Float64} @0x000000010df5b890)

In [15]:
# changing y also changes x
y[:, 1] .= 0  # Dot broadcasting: "vectorization" in Julia. More below
x

5×5 Matrix{Float64}:
 0.0   0.540629   0.003503  -0.0534454   0.382545
 0.0   0.876571   0.0        1.84941     0.567994
 0.0   0.313884  -0.306218  -1.77579    -0.088558
 0.0  -1.18005   -0.895966   0.217129    0.816159
 0.0  -1.44407    0.318821  -0.211098   -0.322778

In [16]:
# create a new copy of data
z = copy(x)

5×5 Matrix{Float64}:
 0.0   0.540629   0.003503  -0.0534454   0.382545
 0.0   0.876571   0.0        1.84941     0.567994
 0.0   0.313884  -0.306218  -1.77579    -0.088558
 0.0  -1.18005   -0.895966   0.217129    0.816159
 0.0  -1.44407    0.318821  -0.211098   -0.322778

In [17]:
pointer(x), pointer(z)  # they should be different now

(Ptr{Float64} @0x000000010df5b890, Ptr{Float64} @0x000000010dee4ef0)

In [18]:
a = 1.0  # Float64
b = a
b

1.0

In [19]:
a = 2.0
b

1.0

#### What's the difference between `(x, y)` and `(a, b)`?

- In Julia, everything is an object (see **Types** below). But there are *mutable* and *immutable* objects.
- In *assignment* of the form `x = ...`, the LHS is a variable name. Assignment changes which object the variable `x` refers to (called a *variable binding*). 
- After the statement `b = a` any change to `a` also affects `b`. However, the value bound to `a` is `1.0`, an immutable value. 
- You can't mutate an immutable object. The next statement `a = 2.0` does *not* mutate the value bound to `a` (`1.0`), but create a new immutable object `2.0` and re-binds it to variable `a`.
- Binding of `b` to the previous object (`1.0`) is not affected. Hence there's no way to tell if it was copied or referenced.

In [20]:
# guess what will happen
x = randn(5, 5)
y

5×5 Matrix{Float64}:
 0.0   0.540629   0.003503  -0.0534454   0.382545
 0.0   0.876571   0.0        1.84941     0.567994
 0.0   0.313884  -0.306218  -1.77579    -0.088558
 0.0  -1.18005   -0.895966   0.217129    0.816159
 0.0  -1.44407    0.318821  -0.211098   -0.322778

- On the other hand, `Array` is a mutable object.
- `y[:, 1] .= 0` is *not* an assignment, but a *mutation*.
- `x = x .+ 0.1` is an assignment, whereas `x .+= 0.1` is a mutation.

In [21]:
y = x

5×5 Matrix{Float64}:
  0.998984   0.87657   -0.690889  -1.06172   -0.159721
  0.929669  -0.328722   0.360445  -0.458888   1.76988
 -1.08809    0.184285   0.34641   -0.74648   -0.642978
  2.46141   -2.10293   -0.796035   0.457213  -0.24917
  1.13966   -0.173782   0.29544    1.37726   -0.745195

In [22]:
x .+= 0.1
y

5×5 Matrix{Float64}:
  1.09898    0.97657   -0.590889  -0.961718  -0.0597211
  1.02967   -0.228722   0.460445  -0.358888   1.86988
 -0.988094   0.284285   0.44641   -0.64648   -0.542978
  2.56141   -2.00293   -0.696035   0.557213  -0.14917
  1.23966   -0.073782   0.39544    1.47726   -0.645195

In [23]:
(pointer(x), pointer(y))

(Ptr{Float64} @0x000000014052ad50, Ptr{Float64} @0x000000014052ad50)

In [24]:
x = x .+ 0.1
y

5×5 Matrix{Float64}:
  1.09898    0.97657   -0.590889  -0.961718  -0.0597211
  1.02967   -0.228722   0.460445  -0.358888   1.86988
 -0.988094   0.284285   0.44641   -0.64648   -0.542978
  2.56141   -2.00293   -0.696035   0.557213  -0.14917
  1.23966   -0.073782   0.39544    1.47726   -0.645195

In [25]:
(pointer(x), pointer(y))

(Ptr{Float64} @0x0000000140ee3bf0, Ptr{Float64} @0x000000014052ad50)

### Concatenate matrices

In [26]:
# 1-by-3 array
[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [27]:
# 3-by-1 vector
[1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [28]:
# multiple assignment by tuple
x, y, z = randn(5, 3), randn(5, 2), randn(3, 5)

([0.5893655425511126 0.6478463785075559 0.03675617824627964; 0.32449020240765014 -1.3163416879826713 0.7448429375816905; … ; 1.194345878009456 -0.9709295240318928 0.27695790432451756; -0.22659842128747293 0.1532435439941793 -0.2784639103102133], [1.2488575126330914 -0.8703644138107955; 0.12338420649841966 1.651334800014632; … ; 0.8705337197294406 0.6799072095463546; -1.6574340081943586 -0.3700243675300325], [0.03348929176386288 0.12239273748998791 … -1.6728049527623698 0.5027256700275959; -0.3717281295214447 -0.5438233836426857 … -0.7034641699877021 1.3487199200482247; 0.049027792124969646 0.23817850370798085 … -0.5161662385770864 -0.08535374403107002])

In [29]:
[x y] # 5-by-5 matrix

5×5 Matrix{Float64}:
  0.589366   0.647846   0.0367562   1.24886   -0.870364
  0.32449   -1.31634    0.744843    0.123384   1.65133
 -1.50004   -0.471809  -0.557907    0.278123   1.56953
  1.19435   -0.97093    0.276958    0.870534   0.679907
 -0.226598   0.153244  -0.278464   -1.65743   -0.370024

In [30]:
[x y; z] # 8-by-5 matrix

8×5 Matrix{Float64}:
  0.589366    0.647846   0.0367562   1.24886   -0.870364
  0.32449    -1.31634    0.744843    0.123384   1.65133
 -1.50004    -0.471809  -0.557907    0.278123   1.56953
  1.19435    -0.97093    0.276958    0.870534   0.679907
 -0.226598    0.153244  -0.278464   -1.65743   -0.370024
  0.0334893   0.122393   1.5489     -1.6728     0.502726
 -0.371728   -0.543823  -0.71427    -0.703464   1.34872
  0.0490278   0.238179   0.122957   -0.516166  -0.0853537

### Dot operation

In Julia, any function `f(x)` can be applied elementwise to an array `X` with the “dot call” syntax `f.(X)`. 

In [31]:
x = randn(5, 3)

5×3 Matrix{Float64}:
  0.311722  -0.602978   -1.41185
 -2.95531    1.06727     2.73063
 -1.4536    -1.68355    -0.195356
  0.728974   0.0607037  -1.21232
 -1.16299   -0.388626    1.52238

In [32]:
y = ones(5, 3)

5×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [33]:
x .* y # same as x * y in R

5×3 Matrix{Float64}:
  0.311722  -0.602978   -1.41185
 -2.95531    1.06727     2.73063
 -1.4536    -1.68355    -0.195356
  0.728974   0.0607037  -1.21232
 -1.16299   -0.388626    1.52238

In [34]:
x .^ (-2) # same as x^(-2) in R

5×3 Matrix{Float64}:
 10.2912      2.7504     0.501673
  0.114497    0.877916   0.134114
  0.473274    0.352816  26.2028
  1.88181   271.375      0.680402
  0.739343    6.6212     0.431474

In [35]:
sin.(x)  # same as sin(x) in R

5×3 Matrix{Float64}:
  0.306698  -0.567098   -0.987395
 -0.185207   0.875885    0.399488
 -0.99314   -0.99365    -0.194116
  0.666105   0.0606664  -0.936433
 -0.917994  -0.378917    0.998828

### Basic linear algebra

In [36]:
x = randn(5)

5-element Vector{Float64}:
 0.34146810589642673
 1.4981812185148902
 0.25078117390294813
 0.8568548966734539
 0.2612026843555233

In [37]:
using LinearAlgebra
# vector L2 norm
norm(x)

1.7962365613435223

In [38]:
# same as
sqrt(sum(abs2, x))

1.7962365613435223

In [39]:
y = randn(5) # another vector
# dot product
dot(x, y) # x' * y

-0.24788199560261587

In [40]:
# same as
x'y

-0.24788199560261587

In [41]:
x, y = randn(5, 3), randn(3, 2)
# matrix multiplication, same as %*% in R
x * y

5×2 Matrix{Float64}:
  1.22666    -3.08629
  0.0207958  -1.48039
  1.37031     0.290835
 -2.12267    -0.710753
 -1.52756    -1.22875

In [42]:
x = randn(3, 3)

3×3 Matrix{Float64}:
 -0.821948  -0.417438   0.164008
 -0.117837   1.70361    0.804793
  0.214691  -0.0478425  0.750179

In [43]:
# conjugate transpose
x'

3×3 adjoint(::Matrix{Float64}) with eltype Float64:
 -0.821948  -0.117837   0.214691
 -0.417438   1.70361   -0.0478425
  0.164008   0.804793   0.750179

In [44]:
b = rand(3)
x'b # same as x' * b

3-element Vector{Float64}:
 -0.35187236916572584
  0.9070636015135449
  1.1667751942065532

In [45]:
# trace
tr(x)

1.631839797585085

In [46]:
det(x)

-1.2501936512996823

In [47]:
rank(x)

3

### Sparse matrices

In [48]:
using SparseArrays

# 10-by-10 sparse matrix with sparsity 0.1
X = sprandn(10, 10, .1)

10×10 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅   -2.05379   ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅   -1.12422  0.495726
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 

Question: why do we use `SparseArrays`?

In [49]:
# convert to dense matrix; be cautious when dealing with big data
Xfull = convert(Matrix{Float64}, X)

10×10 Matrix{Float64}:
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0  -2.05379  0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0  -1.12422  0.495726
 0.0  0.0   0.0      0.0  0.0  0.0  0.0  0.0   0.0      0.0

In [50]:
# convert a dense matrix to sparse matrix
sparse(Xfull)

10×10 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅   -2.05379   ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅   -1.12422  0.495726
  ⋅    ⋅     ⋅        ⋅    ⋅    ⋅    ⋅    ⋅     ⋅        ⋅ 

In [51]:
# syntax for sparse linear algebra is the same as dense linear algebra
β = ones(10)
X * β

10-element Vector{Float64}:
  0.0
 -2.0537854136532983
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
 -0.6284968672903815
  0.0

In [52]:
# many functions apply to sparse matrices as well
sum(X)

-2.6822822809436797

## Control flow and loops

* if-elseif-else-end

```julia
if condition1
    # do something
elseif condition2
    # do something
else
    # do something
end
```

* `for` loop

```julia
for i in 1:10
    println(i)
end
```

* Nested `for` loop:

```julia
for i in 1:10
    for j in 1:5
        println(i * j)
    end
end
```
Same as

```julia
for i in 1:10, j in 1:5
    println(i * j)
end
```

* Exit loop:

```julia
for i in 1:10
    # do something
    if condition1
        break # skip remaining loop
    end
end
```

* Exit iteration:  

```julia
for i in 1:10
    # do something
    if condition1
        continue # skip to next iteration
    end
    # do something
end
```

## Functions 

* Function definition
```julia
function func(req1, req2; key1=dflt1, key2=dflt2)
    # do stuff
    return out1, out2, out3
end
```
    - **Required arguments** are separated with a comma and use the positional notation.  
    - **Optional arguments** need a default value in the signature.  
    - **Semicolon** is not required in function call.  
    - **return** statement is optional (value of the last expression is the return value, like R).  
    - Multiple outputs can be returned as a **tuple**, e.g., `return out1, out2, out3`.  

* In Julia, all arguments to functions are [**passed by reference**](https://en.wikipedia.org/wiki/Evaluation_strategy#Call_by_reference), in contrast to R and Matlab (which use pass by value).
    - Implication: function arguments can be **modified** inside the function.

* By convention function names ending with `!` indicates that function mutates at least one argument, typically the first.
```julia
sort!(x) # vs sort(x)
```

* There is a subtle binding issue (see the Indexing section above) in functions; see the "I passed an argument `x` to a function, modified it inside that function, but on the outside, the variable `x` is still unchanged. Why?" section of  https://docs.julialang.org/en/v1/manual/faq/

* Anonymous functions, e.g., `x -> x^2`, is commonly used in collection function or list comprehensions.
```julia
map(x -> x^2, y) # square each element in x
```

* Functions can be nested:

```julia
function outerfunction()
    # do some outer stuff
    function innerfunction()
        # do inner stuff
        # can access prior outer definitions
    end
    # do more outer stuff
end
```

* Functions can be vectorized using the "dot call" syntax:

In [53]:
function myfunc(x)
    return sin(x^2)
end

x = randn(5, 3)
myfunc.(x)

5×3 Matrix{Float64}:
  0.253517   0.979067     0.0117348
  0.118159   0.00956257   0.0499083
 -0.98609   -0.195548     0.284757
  0.789984   0.000642589  0.988788
  0.546603   0.0826408    0.357081

* **Collection function** (think this as the series of `apply` functions in R).

    Apply a function to each element of a collection:

```julia
map(f, coll) # or
map(coll) do elem
    # do stuff with elem
    # must contain return
end
```

In [54]:
map(x -> sin(x^2), x)   # same as above

5×3 Matrix{Float64}:
  0.253517   0.979067     0.0117348
  0.118159   0.00956257   0.0499083
 -0.98609   -0.195548     0.284757
  0.789984   0.000642589  0.988788
  0.546603   0.0826408    0.357081

In [55]:
map(x) do elem   # long version of above
    elem = elem^2
    return sin(elem)
end

5×3 Matrix{Float64}:
  0.253517   0.979067     0.0117348
  0.118159   0.00956257   0.0499083
 -0.98609   -0.195548     0.284757
  0.789984   0.000642589  0.988788
  0.546603   0.0826408    0.357081

In [56]:
# Mapreduce
mapreduce(x -> sin(x^2), +, x)   # mapreduce(mapper, reducer, data)

3.2908069925088776

In [57]:
# same as
sum(x -> sin(x^2), x)

3.2908069925088776

* List **comprehension**

In [58]:
[sin(2i + j) for i in 1:5, j in 1:3] # similar to Python

5×3 Matrix{Float64}:
  0.14112   -0.756802  -0.958924
 -0.958924  -0.279415   0.656987
  0.656987   0.989358   0.412118
  0.412118  -0.544021  -0.99999
 -0.99999   -0.536573   0.420167

## Type system

* Every variable in Julia has a type.

* When thinking about types, think about sets.

* Everything is a subtype of the abstract type `Any`.

* An abstract type defines a set of types
    - Consider types in Julia that are a `Number`:
<img src="1280px-Type-hierarchy-for-julia-numbers.png" width="800" align="center"/>
    - source: https://en.wikibooks.org/wiki/Introducing_Julia/Types

* We can explore type hierarchy with `typeof()`, `supertype()`, and `subtypes()`.

In [59]:
typeof(1.0), typeof(1)

(Float64, Int64)

In [60]:
supertype(Float64)

AbstractFloat

In [61]:
subtypes(AbstractFloat)

4-element Vector{Any}:
 BigFloat
 Float16
 Float32
 Float64

In [62]:
# Is Float64 a subtype of AbstractFloat?
Float64 <: AbstractFloat

true

In [63]:
# On 64bit machine, Int == Int64
Int == Int64

true

In [64]:
# convert to Float64
convert(Float64, 1)

1.0

In [65]:
# same as
Float64(1)

1.0

In [66]:
# Float32 vector
x = randn(Float32, 5)

5-element Vector{Float32}:
 -0.6000053
  0.57898515
 -1.9387985
 -0.04535096
  0.9868613

In [67]:
# convert to Float64
convert(Array{Float64}, x)

5-element Vector{Float64}:
 -0.6000053286552429
  0.5789851546287537
 -1.9387985467910767
 -0.04535096138715744
  0.9868612885475159

In [68]:
# same as
Float64.(x)

5-element Vector{Float64}:
 -0.6000053286552429
  0.5789851546287537
 -1.9387985467910767
 -0.04535096138715744
  0.9868612885475159

In [69]:
# convert Float64 to Int64
convert(Int, 1.0)

1

In [70]:
convert(Int, 1.5) # should use round(1.5)

LoadError: InexactError: Int64(1.5)

In [71]:
round(Int, 1.5)

2

## Multiple dispatch

* [Multiple dispatch](https://en.wikipedia.org/wiki/Multiple_dispatch) is a feature of some programming languages in which a function or method can be dynamically dispatched based on the run time (dynamic) type or, in the more general case, some other attribute of more than one of its arguments.

* Multiple dispatch lies in the core of Julia design. It allows built-in and user-defined functions to be overloaded for different combinations of argument types.

* In Juila, methods belong to functions, called **generic functions**.

* Let's consider a simple "doubling" function:

In [72]:
g(x) = x + x

g (generic function with 1 method)

In [73]:
g(1.5)

3.0

This definition is too broad, since some things, e.g., strings, can't be added 

In [74]:
g("hello world")

LoadError: MethodError: no method matching +(::String, ::String)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:560

* This definition is correct but too restrictive, since any `Number` can be added.

In [75]:
g(x::Float64) = x + x

g (generic function with 2 methods)

* This definition will automatically work on the entire type tree above!

In [76]:
g(x::Number) = x + x

g (generic function with 3 methods)

This is a lot nicer than 
```julia
function g(x)
    if isa(x, Number)
        return x + x
    else
        throw(ArgumentError("x should be a number"))
    end
end
```

* `methods(func)` function display all methods defined for `func`.

In [77]:
methods(g)

# 3 methods for generic function "g":
[1] g(x::Float64) in Main at In[75]:1
[2] g(x::Number) in Main at In[76]:1
[3] g(x) in Main at In[72]:1

* When calling a function with multiple definitions, Julia will search from the narrowest signature to the broadest signature.

* `@which func(x)` marco tells which method is being used for argument signature `x`.

In [78]:
# an Int64 input
@which g(1)

g(x::Number) in Main at In[76]:1

In [79]:
@which g(1.0)

g(x::Float64) in Main at In[75]:1

In [80]:
# a Vector{Float64} input
@which g(randn(5))

g(x) in Main at In[72]:1

* R also makes use of generic functions and multiple dispatch (see http://adv-r.had.co.nz/OO-essentials.html#s3), but it is not fully optimized.

## Just-in-time compilation (JIT)

| <img src="./julia_toolchain.png" alt="Julia toolchain" style="width: 400px;"/> | <img src="./julia_introspect.png" alt="Julia toolchain" style="width: 500px;"/> |
|----------------------------------|------------------------------------|
|||

Source: [Introduction to Writing High Performance Julia](https://youtu.be/szE4txAD8mk) by Arch D. Robinson

* `Julia`'s efficiency results from its capability to infer the types of **all** variables within a function and then call LLVM (compiler) to generate optimized machine code at run-time. 

Consider the `g` (doubling) function defined earlier. This function will work on **any** type which has a method for `+`.

In [81]:
g(2), g(2.0)

(4, 4.0)

**Step 1**: Parse Julia code into [abstract syntax tree (AST)](https://en.wikipedia.org/wiki/Abstract_syntax_tree).

In [82]:
@code_lowered g(2)

CodeInfo(
1 ─ %1 = x + x
└──      return %1
)

**Step 2**: Type inference according to input type.

In [83]:
@code_warntype g(2)

Variables
  #self#::Core.Const(g)
  x::Int64

Body::Int64
1 ─ %1 = (x + x)::Int64
└──      return %1


In [84]:
@code_warntype g(2.0)

Variables
  #self#::Core.Const(g)
  x::Float64

Body::Float64
1 ─ %1 = (x + x)::Float64
└──      return %1


**Step 3**: Compile into **LLVM bytecode** (equivalent of R bytecode generated by the compiler package).

In [85]:
@code_llvm g(2)

;  @ In[76]:1 within `g'
define i64 @julia_g_4079(i64 signext %0) {
top:
; ┌ @ int.jl:87 within `+'
   %1 = shl i64 %0, 1
; └
  ret i64 %1
}


In [86]:
@code_llvm g(2.0)

;  @ In[75]:1 within `g'
define double @julia_g_4104(double %0) {
top:
; ┌ @ float.jl:326 within `+'
   %1 = fadd double %0, %0
; └
  ret double %1
}


We didn't provide a type annotation. But different LLVM code gets generated depending on the argument type!

In R or Python, `g(2)` and `g(2.0)` would use the same code for both.
 
In Julia, `g(2)` and `g(2.0)` dispatches to optimized code for `Int64` and `Float64`, respectively.

For integer input `x`, LLVM compiler is smart enough to know `x + x` is simple shifting `x` by 1 bit, which is faster than addition.
 
* **Step 4**: Lowest level is the **assembly code**, which is machine dependent.

In [87]:
@code_native g(2)

	.section	__TEXT,__text,regular,pure_instructions
; ┌ @ In[76]:1 within `g'
; │┌ @ int.jl:87 within `+'
	leaq	(%rdi,%rdi), %rax
; │└
	retq
	nopw	%cs:(%rax,%rax)
; └


1st instruction adds the content of the general purpose 64-bit register (a small memory inside the CPU) RDI to itself, and load the result into another register RAX. The addition here is the integer arithmetic.

In [88]:
@code_native g(2.0)

	.section	__TEXT,__text,regular,pure_instructions
; ┌ @ In[75]:1 within `g'
; │┌ @ float.jl:326 within `+'
	vaddsd	%xmm0, %xmm0, %xmm0
; │└
	retq
	nopw	%cs:(%rax,%rax)
; └


In [89]:
run(`which /usr/local/bin/R`)

/usr/local/bin/R


Process(`which /usr/local/bin/R`, ProcessExited(0))

1st instruction adds the content of the 128-bit register XMM0 to itself, and overwrites the result into XMM0. The addition here is the floating point arithmetic and a "single instruction, multiple data" (SIMD) instruction.

## Acknowledgment

This lecture note has evolved from [Dr. Hua Zhou](http://hua-zhou.github.io)'s 2019 Winter Statistical Computing course notes available at <http://hua-zhou.github.io/teaching/biostatm280-2019spring/index.html>.